-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=*
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: remove-crlf
        exclude: \Makefile|.(bat)$
    -   id: remove-tabs
        exclude: \Makefile|.(bat)$
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
        exclude: .git/*
        args:
        - --rcfile=.pylintrc
        - "--msg-template={path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"
    -   id: flake8
        name: flake8
        entry: python -m flake8.__main__
        language: system
        files: \.py$
        exclude: .git/*
